# Generated by Django 5.0.6 on 2024-07-23 17:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(db_index=True, default=datetime.datetime(2024, 7, 23, 17, 8, 30, 582619, tzinfo=datetime.timezone.utc), max_length=1000, verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=2, verbose_name='Like Count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, default='Sajid', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Datetime'),
        ),
    ]
